public class am_ItemComponentUseTriggerHandler extends am_TriggerHandler{
  /***********************************************************************************************
   *  Written by:    David Strangward
   *  Date:          17/8/2016
   *  Modified by:
   *  Date Modified:
   *
   *  Description:   Extends the generic TriggerHandler class to provide specific functionality
   *                
   ***********************************************************************************************/  
 
  public am_ItemComponentUseTriggerHandler() {
  }
  
  protected override void afterUpdate() {
//    am_ItemComponentUseAudit newItemComponentUseAudit = new am_ItemComponentUseAudit();
//    newItemComponentUseAudit.addItemComponentUseAudit(trigger.new);
//    am_ItemComponentUseAudit.addItemComponentUseAudit((List<Item_Component_Use__c>)trigger.new);
    }
}